### ISSUE TITLE
Trimmed Toolbar when navigating back from Search Activity

### ISSUE THREAD

**Issue by lineargs** [chrisbanes/tivi#493] opened 2019-10-12 18:12 UTC
Steps to reproduce the issue:

- Navigate to search activity
- Close keyboard
- Click on any other activity

The issue does not exist if the Search Activity is open and then open another activity without closing the keyboard.

Video can be found [here](https://drive.google.com/file/d/1TBYqWTKhCj7FIg60SzkuUccV0VB92mSs/view?usp=sharing)

![Screenshot_20191012-185336](https://user-images.githubusercontent.com/3036412/66705870-0a5d4100-ed24-11e9-9bf1-15906eb7cd1a.png)

**Comment by lineargs** [comment] 2019-10-12 18:22
Apologiees, Android 10 running on Pixel XL
Tivi v0.3.6.2

**Comment by chrisbanes** [comment] 2019-10-13 04:54
Weird, I can't reproduce this on my devices or emulators. 

I have seen this before though and it seems to be a weird `ConstraintLayout` bug.

**Comment by nevack** [comment] 2019-10-16 09:38
Same on Galaxy S9+, Android 9

**Comment by chrisbanes** [comment] 2019-11-04 03:05
I can't recreate this on any emulators which is weird. Anyway, I've updated ConstraintLayout to 2.0.0-beta3 so I'm hoping this issue disappears in the next update.

**Comment by chrisbanes** [comment] 2019-11-09 03:22
This should be fixed in v0.4.0

**Closed by chrisbanes** 2019-11-09 03:22 UTC

**Comment by lineargs** [comment] 2019-11-09 09:43
Yes, this is now fixed in v0.4.0. Although I have tested on Pixel4, this was still there on the previous version, but not anymore. Thanks

**Comment by chrisbanes** [comment] 2019-11-09 10:33
Cool, thanks for confirming
